// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEJp0xqpyrpoISNhmwnbhjhFIs93dZX8s',
    appId: '1:1035293505494:web:2eb9e05d44b09c441cd677',
    messagingSenderId: '1035293505494',
    projectId: 'interntrack-33ad5',
    authDomain: 'interntrack-33ad5.firebaseapp.com',
    storageBucket: 'interntrack-33ad5.firebasestorage.app',
    measurementId: 'G-RXDY9GFQRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBGti-tCX2gSklypShheIhHEihl75WeCE',
    appId: '1:1035293505494:android:0c305843e4fa8ef11cd677',
    messagingSenderId: '1035293505494',
    projectId: 'interntrack-33ad5',
    storageBucket: 'interntrack-33ad5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Iierk6sGj7nUvyFYriiIH7_eJK9V-VU',
    appId: '1:1035293505494:ios:ea99716d6e19deab1cd677',
    messagingSenderId: '1035293505494',
    projectId: 'interntrack-33ad5',
    storageBucket: 'interntrack-33ad5.firebasestorage.app',
    iosBundleId: 'com.example.s62122025BinaryFlutterfirebaseInterntrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Iierk6sGj7nUvyFYriiIH7_eJK9V-VU',
    appId: '1:1035293505494:ios:ea99716d6e19deab1cd677',
    messagingSenderId: '1035293505494',
    projectId: 'interntrack-33ad5',
    storageBucket: 'interntrack-33ad5.firebasestorage.app',
    iosBundleId: 'com.example.s62122025BinaryFlutterfirebaseInterntrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEJp0xqpyrpoISNhmwnbhjhFIs93dZX8s',
    appId: '1:1035293505494:web:594e8c6685fcf8511cd677',
    messagingSenderId: '1035293505494',
    projectId: 'interntrack-33ad5',
    authDomain: 'interntrack-33ad5.firebaseapp.com',
    storageBucket: 'interntrack-33ad5.firebasestorage.app',
    measurementId: 'G-9LDFBXP1KN',
  );
}
